name = "laravel"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

port=8000 # Shopify assigns a random port if not specified, but there is no way to let PHP serve with the random port

[commands]
predev = "composer install && npm install"
dev = "php artisan serve --host=localhost --port=8000"
